modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mods]]
modId = "bakery"
version = "${version}"
displayName = "[Let's Do] Bakery"
authors = "satisfy"
credits = "MissLilitu, CR-055"
description = '''
Build your own bakery, bake the finest pastries, delicious bread, and sweet cakes!'''
logoFile = "pack.png"
displayURL = "https://www.lets-do.ch"

[[dependencies.bakery]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bakery]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bakery]]
modId = "farm_and_charm"
type = "required"
versionRange = "[1.1.27,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bakery]]
modId = "foundation"
type = "required"
versionRange = "[1.0.1,)"
ordering = "AFTER"
side = "BOTH"
